import type { Metadata } from 'next';
import { Box } from '@mui/material';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import '../globals.css';
import ThemeRegistry from '../ThemeRegistery';
import Header from '../Components/Organisms/Header';
import Footer from '../Components/Organisms/Footer';

export const metadata: Metadata = {
  title: 'UNITS',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  const dir = locale === 'ar' ? 'rtl' : 'ltr';
  return (
    <html lang={locale} dir={dir}>
      <ThemeRegistry>
        <body>
          <NextIntlClientProvider messages={messages}>
            <Box
              sx={{
                display: 'grid',
                gridTemplateRows: '1fr auto',
                minHeight: '100dvh',
              }}
            >
              <Header />
              <ThemeRegistry>{children}</ThemeRegistry>
              <Footer />
            </Box>
          </NextIntlClientProvider>
        </body>
      </ThemeRegistry>
    </html>
  );
}
